#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = "dev", "master" ]]; then
    echo "Do not push to dev or master branch!!!"
    exit 1
  fi
done